# Generated by Django 5.2.4 on 2025-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeratelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeratelog',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
